src/GoProject.Sample/Models/EndProductNode.cs
using GoProject.Nodes;

namespace GoProject.Sample.Models
{
    public class EndProductNode : EventNode
    {

        public EndProductNode()
        {
            Text = "محصول نهایی";
            EventType = Enums.EventType.Terminate;
            EventDimension = Enums.EventDimension.End;
        }
    }
}

src/GoProject.Sample/Models/ExpenseCenterNode.cs
using System.Collections.ObjectModel;
using GoProject.Nodes;

namespace GoProject.Sample.Models
{
    public class ExpenseCenterNode : PoolNode
    {

        public ExpenseCenterNode()
        {
            Text = "مرکز هزینه";
            Nodes.Add(new SubExpenseCenterNode() { Text = "خط تولید اول" });
        }
    }
}

src/GoProject.Sample/Models/MaterialNode.cs
using System.Collections.Generic;
using GoProject.Nodes;

namespace GoProject.Sample.Models
{
    public class MaterialNode : EventNode
    {
        public MaterialNode()
        {
            Text = "مواد اولیه";
            EventType = Enums.EventType.None;
            EventDimension = Enums.EventDimension.Start;
        }
    }
}

src/GoProject.Sample/Models/SemiFinishMaterialNode.cs
using GoProject.Nodes;

namespace GoProject.Sample.Models
{
    public class SemiFinishMaterialNode : EventNode
    {
        public SemiFinishMaterialNode()
        {
            Text = "مواد نیمه ساخته";
            EventType = Enums.EventType.Multiple;
            EventDimension = Enums.EventDimension.IntermediateNonInter;
        }
    }
}

src/GoProject.Sample/Models/SubExpenseCenterNode.cs
using GoProject.Nodes;

namespace GoProject.Sample.Models
{
    public class SubExpenseCenterNode : LaneNode
    {
        public SubExpenseCenterNode()
        {
            Text = "زیر مرکز هزینه";
        }
    }
}

src/GoProject.Sample/Models/WorkStationNode.cs
using GoProject.Nodes;

namespace GoProject.Sample.Models
{
    public class WorkStationNode : ActivityNode
    {
        public WorkStationNode()
        {
            Text = "ایستگاه کاری";
            TaskType = Enums.TaskType.Service;
        }
    }
}

src/GoProject.Sample/Controllers/BaseController.cs
using System;
using System.Globalization;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace GoProject.Sample.Controllers
{
    public class BaseController : Controller
    {
        public string GetUrlCulture(HttpRequestBase request, bool getDefultCultureIfNotExist = true)
        {
            var path = request.Path;
            if (path.IndexOf("/", StringComparison.Ordinal) != 0 || path.Length < 3)
                return getDefultCultureIfNotExist ? "en" : null;

            return path.Substring(1, 2);
        }

        protected override IAsyncResult BeginExecuteCore(AsyncCallback callback, object state)
        {
            string cultureName = GetUrlCulture(Request); // read route culture?

            CultureInfo culture;
            try
            {
                culture = new CultureInfo(cultureName);
            }
            catch (CultureNotFoundException)
            {
                culture = new CultureInfo("en");
            }

            // Modify current thread's cultures  
            CultureInfo.DefaultThreadCurrentUICulture =
                CultureInfo.DefaultThreadCurrentCulture =
                    Thread.CurrentThread.CurrentCulture =
                        Thread.CurrentThread.CurrentUICulture = culture;

            RouteData.Values["culture"] = cultureName;  // set culture

            return base.BeginExecuteCore(callback, state);
        }
    }
}

src/GoProject.Sample/Controllers/GoApiController.cs
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web.Http;
using GoProject.Nodes;
using GoProject.Sample.Core;
using GoProject.Sample.Models;

namespace GoProject.Sample.Controllers
{
    public class GoApiController : ApiController
    {
        private static string FilePath { get; } = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "GoDiagram.json");

        [HttpPost]
        public IHttpActionResult SaveDiagram([FromBody]Diagram diagram)
        {
            // Save json text on local drives
            var json = JsonConvert.SerializeObject(diagram, Formatting.Indented);
            File.WriteAllText(FilePath, json);
            //
            // Store on Sql Server Database
            if (diagram == null) return InternalServerError(new ArgumentNullException(nameof(diagram)));

            diagram.Name = diagram.Name ?? "TestDiagramName"; // Very important param

            Connections.GoProjectDb.SqlConn.StoreOnDb(diagram, 0);

            return Ok(FilePath);
        }

        public IHttpActionResult GetDiagram()
        {
            var json = File.ReadAllText(FilePath, System.Text.Encoding.UTF8);
            var diagram = JsonConvert.DeserializeObject<Diagram>(json);


            return Ok(diagram);
        }

        public IHttpActionResult GetDiagram(string id)
        {
            //var diagram = Connections.GoProjectDb.SqlConn.LoadFromDb(id);
            var diagram = Connections.CAS.SqlConn.LoadFromCasDb(id);


            return Ok(diagram);
        }

        public IHttpActionResult GetPaletteNodes()
        {
            var diagram = new Diagram
            {
                //TreeNodes = GoHelper.PaletteTreeNodes()
                NodeDataArray = Connections.GoProjectDb.SqlConn.GetPaletteNodesByUserRole(0).ToList()
            };

            return Ok(diagram);
        }

        public IHttpActionResult GetCustomPaletteNodes()
        {
            var parentNode = new ExpenseCenterNode();
            ((IGroupNode) parentNode.Nodes[0]).Nodes = new ObservableCollection<Node>()
            {
                new MaterialNode(),
                new SemiFinishMaterialNode(),
                new EndProductNode(),
                new WorkStationNode()
            };

            var diagram = new Diagram
            {
                TreeNodes = new List<Node>()
                {
                    parentNode
                }
            };
            

            return Ok(diagram);
        }

        public IHttpActionResult GetLocalization()
        {
            var jsonResources = GoProject.Properties.Localization
                .ResourceManager.GetResourceSet(CultureInfo.DefaultThreadCurrentCulture, true, true) 
                .Cast<DictionaryEntry>()
                .ToDictionary(x => x.Key.ToString(),
                         x => x.Value.ToString());
            

            return Ok(jsonResources);
        }
    }
}

src/GoProject.Sample/Controllers/GoController.cs
using System;
using System.Web.Mvc;
using Dapper;
using GoProject.Sample.Core;

namespace GoProject.Sample.Controllers
{
    public class GoController : BaseController
    {
        
        public ActionResult PageFlowSample()
        {
            ViewBag.Title = "PageFlowSample";
            return View();
        }
        
        public ActionResult PlanogramSample()
        {
            ViewBag.Title = "PlanogramSample";
            return View();
        }

        public ActionResult DoubleTreeSample()
        {
            ViewBag.Title = "DoubleTreeSample";
            return View();
        }


        public ActionResult PipesSample()
        {
            ViewBag.Title = "PipesSample";
            return View();
        }

        public ActionResult BpmnEditorSample()
        {
            ViewBag.Title = "BpmnEditorSample";
            return View();
        }

        [HttpPost]
        public ActionResult BpmnEditorSample(string id)
        {
            ViewBag.Title = "BpmnEditorSample";
            // var model = Connections.GoProjectDb.SqlConn.LoadFromDb(id);
            var model = Connections.CAS.SqlConn.LoadFromCasDb(id);

            return View(model);
        }

        public ActionResult GoDiagramsTablePartial()
        {
            //var model = Connections.GoProjectDb.SqlConn.Query<Diagram>("Select * From Diagrams");
            var model = Connections.CAS.SqlConn.Query<Diagram>("SELECT ExpenseCenterId AS Id, [NAME], UserId AS CreatorUserId FROM  dbo.ExpenseCenter");


            return PartialView("_GoDiagramsTablePartial", model);
        }



    }
}

src/GoProject.Sample/Controllers/HomeController.cs
using System;
using System.Web.Mvc;

namespace GoProject.Sample.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            return View();
        }
    }
}

src/GoProject.Sample/Views/Go/BpmnEditorSample.cshtml
@using GoProject.Properties

<div class="row frm">
    <div class="col-xs-2">
        @Html.Action("GoDiagramsTablePartial", "Go")
    </div>

    <div class="col-xs-10">
        
        <div class="row">
            <div id="currentFile">(@Localization.Unsaved)</div>
            <ul id="menuui">
                <li>
                    <a href="#">@Localization.File</a>
                    <ul>
                        <li><a href="#" onclick="newDocument(diagram)">@Localization.New</a></li>
                        <li><a href="#" onclick="loadJSON(diagram, window.location.origin + '/api/goApi/GetPaletteNodes')">@Localization.Palette</a></li>
                        <li><a href="#" onclick="loadJSON(diagram, window.location.origin + '/api/goApi/GetCustomPaletteNodes')">@Localization.CustomePalette</a></li>
                        <li><a href="#" onclick="loadJSON(diagram, window.location.origin + '/api/goApi/GetDiagram')">@Localization.Reset</a></li>
                        <li><a href="#" onclick="saveDocument(diagram, 'api/goApi/SaveDiagram')">@Localization.Save</a></li>
                        <li><a href="#" onclick="diagram.layoutDiagram(true)">@Localization.Layout</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">@Localization.Edit</a>
                    <ul>
                        <li><a href="#" onclick="diagram.commandHandler.undo()">@Localization.Undo</a></li>
                        <li><a href="#" onclick="diagram.commandHandler.redo()">@Localization.Redo</a></li>
                        <li><a href="#" onclick="diagram.commandHandler.cutSelection()">@Localization.Cut</a></li>
                        <li><a href="#" onclick="diagram.commandHandler.copySelection()">@Localization.Copy</a></li>
                        <li><a href="#" onclick="diagram.commandHandler.pasteSelection()">@Localization.Paste</a></li>
                        <li><a href="#" onclick="diagram.commandHandler.deleteSelection()">@Localization.Delete</a></li>
                        <li><a href="#" onclick="diagram.commandHandler.selectAll()">@Localization.SelectAll</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">@Localization.Options</a>
                    <ul>
                        <li>
                            <a href="#">
                                <input id="grid" type="checkbox" name="options" value="grid" onclick="updateGridOption(diagram)">@Localization.Grid
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <input id="snap" type="checkbox" name="options" value="0" onclick="updateSnapOption(diagram)">@Localization.Snapping
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

        <div class="row" id="PaletteAndDiagram" dir="@Localization.Direction">

            <div id="sideBar" class="col-xs-2">
                <div class="handle">@Localization.Overview:</div>
                <div id="myOverviewDiv"></div>

                <div id="accordion">
                    <h4>@Localization.Tools</h4>
                    <div>
                        <div id="myPaletteLevel" class="myPaletteDiv"></div>
                    </div>
                </div>
            </div>

            <div class="col-xs-7" id="myDiagramDiv"></div>
            
            <div class="col-xs-3" style="float: left;">
                <form id="frmNodeEditor" dir="@Localization.Direction"></form>
            </div>

        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/bpmnJs")
    <!-- Load Grid.Mvc libraries -->
    <link href="~/Content/Gridmvc.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/gridmvc.min.js" type="text/javascript"> </script>

    <!-- Initial this diagram dependecies -->
    <script>

        // setup the menubar ---------------------------------------------------
        jQuery("#menuui").menu();
        jQuery(function () {
            jQuery("#menuui").menu({ position: { my: "left top", at: "left top+30" } });
        });
        jQuery("#menuui").menu({
            icons: { submenu: "ui-icon-triangle-1-s" }
        });
        //----------------------------------------------------------------------------

        // load localization
        var diagram;
        jQuery.getJSON(window.location.origin + "/api/goApi/GetLocalization", function (json) {
            diagram = init('/api/goApi/GetPaletteNodes', json);
            updateSnapOption(diagram);
        });

       

        $(function () {
            pageGrids.diagramsGrid.onRowSelect(function (e) {
                loadJSON(diagram, window.location.origin + '/api/goApi/GetDiagram/?id=' + e.row.Id, function () {
                    diagram.model.id = e.row.Id;
                    diagram.model.name = e.row.Name;
                    diagram.layoutDiagram(true);
                });
            });
        });
    </script>
}

src/GoProject.Sample/Views/Go/DoubleTreeSample.cshtml
@section scripts{
    <script id="code">
        function init() {
            if (window.goSamples) goSamples();  // init for these samples -- you don't need to call this
            var $ = go.GraphObject.make;  // for conciseness in defining templates in this function

            myDiagram =
              $(go.Diagram, "myDiagramDiv",  // must be the ID or reference to div
                { initialContentAlignment: go.Spot.Center });

            // define all of the gradient brushes
            var graygrad = $(go.Brush, "Linear", { 0: "#F5F5F5", 1: "#F1F1F1" });
            var bluegrad = $(go.Brush, "Linear", { 0: "#CDDAF0", 1: "#91ADDD" });
            var yellowgrad = $(go.Brush, "Linear", { 0: "#FEC901", 1: "#FEA200" });
            var lavgrad = $(go.Brush, "Linear", { 0: "#EF9EFA", 1: "#A570AD" });

            // define the Node template for non-terminal nodes
            myDiagram.nodeTemplate =
              $(go.Node, "Auto",
                { isShadowed: true },
                // define the node's outer shape
                $(go.Shape, "RoundedRectangle",
                  { fill: graygrad, stroke: "#D8D8D8" },
                  new go.Binding("fill", "color")),
                // define the node's text
                $(go.TextBlock,
                  { margin: 5, font: "bold 11px Helvetica, bold Arial, sans-serif" },
                  new go.Binding("text", "key"))
              );

            // define the Link template
            myDiagram.linkTemplate =
              $(go.Link,  // the whole link panel
                { selectable: false },
                $(go.Shape));  // the link shape

            // create the model for the double tree
            myDiagram.model = new go.TreeModel([
                // these node data are indented but not nested according to the depth in the tree
                { key: "Root", color: lavgrad },
                  { key: "Left1", parent: "Root", dir: "left", color: bluegrad },
                    { key: "leaf1", parent: "Left1" },
                    { key: "leaf2", parent: "Left1" },
                    { key: "Left2", parent: "Left1", color: bluegrad },
                      { key: "leaf3", parent: "Left2" },
                      { key: "leaf4", parent: "Left2" },
                  { key: "Right1", parent: "Root", dir: "right", color: yellowgrad },
                    { key: "Right2", parent: "Right1", color: yellowgrad },
                      { key: "leaf5", parent: "Right1" },
                      { key: "leaf6", parent: "Right1" },
                      { key: "leaf7", parent: "Right2" },
                    { key: "leaf8", parent: "Right1" },
                    { key: "leaf9", parent: "Right1" }
            ]);

            doubleTreeLayout(myDiagram);
        }

        function doubleTreeLayout(diagram) {
            // Within this function override the definition of '$' from jQuery:
            var $ = go.GraphObject.make;  // for conciseness in defining templates
            diagram.startTransaction("Double Tree Layout");

            // split the nodes and links into two Sets, depending on direction
            var leftParts = new go.Set(go.Part);
            var rightParts = new go.Set(go.Part);
            separatePartsByLayout(diagram, leftParts, rightParts);
            // but the ROOT node will be in both collections

            // create and perform two TreeLayouts, one in each direction,
            // without moving the ROOT node, on the different subsets of nodes and links
            var layout1 =
              $(go.TreeLayout,
                {
                    angle: 180,
                    arrangement: go.TreeLayout.ArrangementFixedRoots,
                    setsPortSpot: false
                });

            var layout2 =
              $(go.TreeLayout,
                {
                    angle: 0,
                    arrangement: go.TreeLayout.ArrangementFixedRoots,
                    setsPortSpot: false
                });

            layout1.doLayout(leftParts);
            layout2.doLayout(rightParts);

            diagram.commitTransaction("Double Tree Layout");
        }

        function separatePartsByLayout(diagram, leftParts, rightParts) {
            var root = diagram.findNodeForKey("Root");
            if (root === null) return;
            // the ROOT node is shared by both subtrees!
            leftParts.add(root);
            rightParts.add(root);
            // look at all of the immediate children of the ROOT node
            root.findTreeChildrenNodes().each(function (child) {
                // in what direction is this child growing?
                var dir = child.data.dir;
                var coll = (dir === "left") ? leftParts : rightParts;
                // add the whole subtree starting with this child node
                coll.addAll(child.findTreeParts());
                // and also add the link from the ROOT node to this child node
                coll.add(child.findTreeParentLink());
            });
        }
        init();
    </script>
}

<div id="sample">
    <h3>GoJS Double Tree</h3>
    <div id="myDiagramDiv" style="background-color: white; border: solid 1px black; width: 100%; height: 500px"></div>
    <p>
        This sample displays a diagram of two trees sharing a single root node growing in opposite directions.
        The immediate child data of the ROOT node have a "dir" property
        that describes the direction that subtree should grow.
    </p>
    <p>
        Unlike many <b>GoJS</b> apps, there is no <a>Diagram.layout</a> assigned.
        Layouts are performed in code -- a separate <a>TreeLayout</a> for each subtree.
        Each tree layout works on a subset of the nodes.
        The <b>separatePartsByLayout</b> function produces two separate collections of Nodes and Links,
        one for each direction, and thus one for each tree layout.
    </p>
</div>

src/GoProject.Sample/Views/Go/_GoDiagramsTablePartial.cshtml
@using GridMvc.Html
@model IEnumerable<GoProject.Diagram>

@Html.Grid(Model).Named("diagramsGrid").Columns(columns =>
{
    columns.Add(d => d.Id).Titled("Diagram Id").SetWidth(20).Sortable(true);
    columns.Add(d => d.Name).Titled("Diagram Name").SetWidth(110).Sortable(true);
}).WithPaging(10)

src/GoProject.Sample/Views/Home/Index.cshtml
<div class="container-fluid">
    <div class="row text-center bg-success">
        <h3>
            This is not related to main <a href="https://gojs.net/latest/index.html">GoJS Project Company</a>
        </h3>
    </div>
    <div class="row text-center mt30">
        <div class="col-md-12">
            <div style="display: inline-block;">
                <a class="imagelink" href="https://gojs.net/latest/samples/flowchart.html"><img src="https://gojs.net/latest/assets/images/site1.png" class="img-thumbnail" alt="Flowchart" /></a>
                <a class="imagelink" href="https://gojs.net/latest/samples/stateChart.html"><img src="https://gojs.net/latest/assets/images/site6.png" class="img-thumbnail" alt="State Chart" /></a>
            </div>
            <div style="display: inline-block;">
                <a class="imagelink" href="https://gojs.net/latest/samples/sankey.html"><img src="https://gojs.net/latest/assets/images/site2.png" class="img-thumbnail" alt="Sankey Diagram" /></a>
                <a class="imagelink" href="https://gojs.net/latest/samples/leaflet.html"><img src="https://gojs.net/latest/assets/images/site5.png" class="img-thumbnail" alt="Leaflet Map" /></a>
            </div>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-12">
            <div style="display: inline-block;">
                <a class="imagelink" href="https://gojs.net/latest/samples/orgChartEditor.html"><img src="https://gojs.net/latest/assets/images/site3.png" class="img-thumbnail" alt="Org Chart" /></a>
                <a class="imagelink" href="https://gojs.net/latest/samples/dynamicPorts.html"><img src="https://gojs.net/latest/assets/images/site7.png" class="img-thumbnail" alt="Dynamic Ports Demo" /></a>
            </div>
            <div style="display: inline-block;">
                <a class="imagelink" href="https://gojs.net/latest/samples/dataVisualization.html"><img src="https://gojs.net/latest/assets/images/site4.png" class="img-thumbnail" alt="Data Visualization" /></a>
                <a class="imagelink" href="https://gojs.net/latest/samples/regrouping.html"><img src="https://gojs.net/latest/assets/images/site8.png" class="img-thumbnail" alt="Regrouping Demo" /></a>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row mt30 center-block">
        <p>
            <b>GoJS</b> is a feature-rich JavaScript library for implementing custom interactive diagrams and complex visualizations
            across modern web browsers and platforms.
            <b>GoJS</b> makes constructing JavaScript diagrams of complex nodes, links, and groups easy with customizable templates and layouts.

        <p>
            <b>GoJS</b> offers many advanced features for user interactivity such as drag-and-drop, copy-and-paste,
            in-place text editing, tooltips, context menus, automatic layouts, templates, data binding and models, transactional state and undo management,
            palettes, overviews, event handlers, commands, and an extensible tool system for custom operations.

        <p>
            <b>GoJS</b> is pure JavaScript, so users get interactivity without requiring round-trips to servers and without plugins.
            <b>GoJS</b> normally runs completely in the browser, rendering to an HTML5 Canvas element or SVG without any server-side requirements.
            <b>GoJS</b> does not depend on any JavaScript libraries or frameworks, so it should work with any HTML or JavaScript framework or with no framework at all.

        <p>
            Build custom modeling environments and domain-specific visual languages using the powerful features of <b>GoJS</b>.
            Provide both a system editor and a read-only status monitor using shared code and templates.
            Simultaneously show alternative visualizations of the same data in different diagrams.
            Implement drill-down using expansion of subtrees and subgraphs or a detailed view in another diagram.

        <p>
            Yet <b>GoJS</b> is remarkably simple for such a powerful and flexible system.
            Many pages of documentation introduce the basic concepts and demonstrate typical features that most apps want to offer.
            Nodes and links can be arbitrarily detailed according to the needs of the application.
            The API consists of only a few dozen important classes which encapsulate many useful features that interact with each other.
            There are many properties that permit simple customizations; some methods may be overridden for more complicated customizations.
    </div>
    <div class="row mt30 center-block">
        <div class="col-md-6">
            <h2>Explore</h2>
            <p>
                Run over 150 sample apps that are flowcharts, org charts, mind maps,
                UML diagrams, BPMN diagrams, graph editors, data visualization, and much more.
            </p>
            <p><a class="btn btn-primary" href="https://gojs.net/latest/samples/index.html" role="button">Run Interactive Samples</a></p>
        </div>
        <div class="col-md-6">
            <h2>Learn</h2>
            <p>
                Get started with a step-by-step description of how to build a JavaScript diagram in HTML
                using <b>GoJS</b> and some model data.
            </p>
            <p><a class="btn btn-primary" href="https://gojs.net/latest/learn/index.html" role="button">Learn with GoJS Tutorials</a></p>
        </div>
    </div>
    <div class="row center-block">
        <div class="col-md-6">
            <h2>Download</h2>
            <p>
                Get a copy of the library and all of the samples, extensions, and documentation.
                Search the JavaScript code and modify the samples to start your app.
            </p>
            <p>
                <a class="btn btn-primary" href="https://gojs.net/latest/doc/download.html" role="button">Download</a>
                <a class="btn btn-primary" href="https://github.com/NorthwoodsSoftware/GoJS" role="button">Clone us from GitHub</a>
                <a class="btn btn-primary" href="https://www.npmjs.com/package/gojs" role="button">Install via npm</a>
            </p>
        </div>
        <div class="col-md-6">
            <h2>Technical Introduction</h2>
            <p>
                Read our introduction for a overview of <b>GoJS</b> concepts and features,
                including hundreds of live interactive examples embedded right in each page.
            </p>
            <p><a class="btn btn-primary" href="https://gojs.net/latest/intro/index.html" role="button">Read the Introduction</a></p>
        </div>
    </div>
    <div class="row center-block">
        <div class="col-md-6">
            <h2>Unlimited Evaluation</h2>
            <p>
                Evaluate the full library without any limitations.
                Register with us and get free support for a month to help build your app.
            </p>
            <p>
                <a class="btn btn-primary" href="https://www.nwoods.com/products/register.html" role="button">Register for Support</a>
                <a class="btn btn-primary" href="https://www.nwoods.com/contact.html" role="button">Contact Us</a>
            </p>
        </div>
        <div class="col-md-6">
            <h2>API Documentation</h2>
            <p>
                Read our comprehensive documentation for an in-depth reference of the properties
                and methods of all of the JavaScript classes.
            </p>
            <p><a class="btn btn-primary" href="https://gojs.net/latest/api/index.html" role="button">View the API</a></p>
        </div>
    </div>
    <div class="row mt30 center-block">
        <p>
            When upgrading to a newer version, please read the <strong><a href="https://gojs.net/latest/doc/changelog.html" target="_blank">Change Log</a></strong>.
        </p>
        <p>
            You can explore the newest features and samples in the <a href="https://gojs.net/beta/index.html" target="_blank">GoJS Beta</a> for the next version,
            if a next version is available.  Read the <a href="https://gojs.net/beta/doc/changelog.html" target="_blank">beta change log</a> for the new features.
            Please note that our <a href="https://github.com/NorthwoodsSoftware/GoJS" target="_blank">GitHub</a> directory does not have the beta files.
        </p>
    </div>
    <hr>
</div> <!-- /container -->

src/GoProject.Sample/Views/Shared/_Layout.cshtml
@{
    var version = "v" + typeof(MvcApplication).Assembly.GetName().Version.ToString(3);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Go Project</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/goCss")

    @RenderSection("styles", required: false)

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/goJs")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class = "navbar-brand">Go MVC Project <small>@version</small></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Page Flow", "PageFlowSample", "Go")</li>
                    <li>@Html.ActionLink("Double Tree", "DoubleTreeSample", "Go")</li>
                    <li>@Html.ActionLink("BPMN Editor", "BpmnEditorSample", "Go")</li>
                    <li>@Html.ActionLink("Pipes", "PipesSample", "Go")</li>
                    <li>@Html.ActionLink("Planogram", "PlanogramSample", "Go")</li>
                </ul>
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>